insert into apps.CALC_DISTR_FORMATION_METHODS (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('LOCALLY', 1, null, null, null);

insert into apps.CALC_DISTR_FORMATION_METHODS (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('UPWARDS', 1, null, null, null);
