insert into APPS.DICT_CTDE_INFLUENCE_DEGREES_TL (CODE, LANG, NAME, CREATE_BY, CREATE_DATE)
values ('INCREASES', 'RU', 'увеличивает', 1, '07.07.2019 00:00:00');

insert into APPS.DICT_CTDE_INFLUENCE_DEGREES_TL (CODE, LANG, NAME, CREATE_BY, CREATE_DATE)
values ('INCREASES', 'KZ', 'увеличивает', 1, '07.07.2019 00:00:00');

insert into APPS.DICT_CTDE_INFLUENCE_DEGREES_TL (CODE, LANG, NAME, CREATE_BY, CREATE_DATE)
values ('DECREASES', 'RU', 'уменьшает', 1, '07.07.2019 00:00:00');

insert into APPS.DICT_CTDE_INFLUENCE_DEGREES_TL (CODE, LANG, NAME, CREATE_BY, CREATE_DATE)
values ('DECREASES', 'KZ', 'уменьшает', 1, '07.07.2019 00:00:00');

insert into APPS.DICT_CTDE_INFLUENCE_DEGREES_TL (CODE, LANG, NAME, CREATE_BY, CREATE_DATE)
values ('NONE', 'RU', 'не влияет', 1, '07.07.2019 00:00:00');

insert into APPS.DICT_CTDE_INFLUENCE_DEGREES_TL (CODE, LANG, NAME, CREATE_BY, CREATE_DATE)
values ('NONE', 'KZ', 'не влияет', 1, '07.07.2019 00:00:00');