ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'dd.mm.yyyy HH24:MI:SS';

insert into apps.DICT_DELIVERY_ASSIGNMENTS (ID, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values (1, 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_ASSIGNMENTS (ID, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values (2, 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_ASSIGNMENTS (ID, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values (3, 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_ASSIGNMENTS (ID, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values (4, 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_ASSIGNMENTS (ID, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values (5, 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_ASSIGNMENTS (ID, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values (6, 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_ASSIGNMENTS (ID, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values (7, 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_ASSIGNMENTS (ID, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values (8, 1, '14.07.2019 00:00:00', null, null);
