ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'dd.mm.yyyy HH24:MI:SS';

insert into apps.DICT_DELIVERY_TYPES (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('IMPORT', 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_TYPES (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('EXPORT', 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_TYPES (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('INTERNAL', 1, '14.07.2019 00:00:00', null, null);
