ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'dd.mm.yyyy HH24:MI:SS';

insert into apps.DICT_DEALINGS_TYPES (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('CB', 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DEALINGS_TYPES (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('CB-DOD', 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DEALINGS_TYPES (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('CB-DA', 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DEALINGS_TYPES (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('CB-DMS', 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DEALINGS_TYPES (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('WB', 1, '14.07.2019 00:00:00', null, null);
