ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'dd.mm.yyyy HH24:MI:SS';

insert into apps.DICT_DELIVERY_TYPES_TL (DELIVERY_TYPE_CODE, LANG, NAME, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('IMPORT', 'RU', 'импорт', 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_TYPES_TL (DELIVERY_TYPE_CODE, LANG, NAME, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('IMPORT', 'KZ', 'импорт', 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_TYPES_TL (DELIVERY_TYPE_CODE, LANG, NAME, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('EXPORT', 'RU', 'экспорт', 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_TYPES_TL (DELIVERY_TYPE_CODE, LANG, NAME, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('EXPORT', 'KZ', 'экспорт', 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_TYPES_TL (DELIVERY_TYPE_CODE, LANG, NAME, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('INTERNAL', 'RU', 'внутри РК', 1, '14.07.2019 00:00:00', null, null);

insert into apps.DICT_DELIVERY_TYPES_TL (DELIVERY_TYPE_CODE, LANG, NAME, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('INTERNAL', 'KZ', 'внутри РК', 1, '14.07.2019 00:00:00', null, null);
