insert into APPS.RES_DATA_TYPES (CODE, PRIORITY, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('FINAL', 1, 1, null, 1, null);

insert into APPS.RES_DATA_TYPES (CODE, PRIORITY, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('OPER', 2, 1, null, 1, null);
