create or replace view apps_cfg.res_time_series_v as
select h.id,
       h.start_datetime,
       h.end_datetime,
       h.resolution,
       h.version,
       h.is_active,
       h.time_series_type,
       tst.name as time_series_type_str,
       h.contract_id,
       (select d.doc_number from apps.cm_doc_keg_cte d where d.id = h.contract_id) as contract_str,
       h.bp_id,
       (select bp.short_name from apps.dict_business_partners_tl bp where bp.id = h.bp_id and bp.lang = adm_cfg.adm_locale) as bp_str,
       h.energy_source_id,
       (select e.short_name from apps.dict_energy_sources_tl e where e.id = h.energy_source_id and e.lang = adm_cfg.adm_locale) as energy_source_str,
       h.total,
       h.unit_id,
       h.create_by,
       h.create_date,
       h.last_update_by,
       h.last_update_date,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 1 ) as val_01,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 2 ) as val_02,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 3 ) as val_03,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 4 ) as val_04,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 5 ) as val_05,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 6 ) as val_06,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 7 ) as val_07,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 8 ) as val_08,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 9 ) as val_09,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 10 ) as val_10,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 11 ) as val_11,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 12 ) as val_12,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 13 ) as val_13,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 14 ) as val_14,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 15 ) as val_15,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 16 ) as val_16,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 17 ) as val_17,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 18 ) as val_18,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 19 ) as val_19,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 20 ) as val_20,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 21 ) as val_21,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 22 ) as val_22,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 23 ) as val_23,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id and l.pos = 24 ) as val_24,
      (select sum(l.val) from apps.res_time_series_lines l where l.header_id = h.id)                 as itogo
from apps.res_time_series_header h
join APPS.RES_TIME_SERIES_TYPES_tl  tst on tst.code = h.time_series_type and tst.lang = adm_cfg.adm_locale