insert into apps.CALC_DISTR_METHODS (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('FORMULA', 1, null, null, null);

insert into apps.CALC_DISTR_METHODS (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('DISTR_RULE', 1, null, null, null);
