insert into apps.CALC_DISTR_FRML_WAYS_CREATE (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('MANUAL', 1, null, null, null);

insert into apps.CALC_DISTR_FRML_WAYS_CREATE (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('DISTR_RULE', 1, null, null, null);

insert into apps.CALC_DISTR_FRML_WAYS_CREATE (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('AUTO', 1, null, null, null);