insert into apps.DICT_ENERGY_SOURCE_TYPE2 (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('INTERNAL', 1, null, null, null);

insert into apps.DICT_ENERGY_SOURCE_TYPE2 (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('EXTERNAL', 1, null, null, null);
