
insert into apps.CALC_DISTR_RULE_METHODS (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('DECLARED VOLUME', 1, null, null, null);

insert into apps.CALC_DISTR_RULE_METHODS (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('PROPORTION', 1, null, null, null);

insert into apps.CALC_DISTR_RULE_METHODS (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('IN FACT', 1, null, null, null);

insert into apps.CALC_DISTR_RULE_METHODS (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('FORMULA', 1, null, null, null);

insert into apps.CALC_DISTR_RULE_METHODS (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('MANUAL', 1, null, null, null);
