insert into apps.CALC_DISTR_RULE_METHODS (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('NONE', 1, null, null, null);

insert into apps.CALC_DISTR_RULE_METHODS (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('FIX VALUE', 1, null, null, null);

insert into apps.CALC_DISTR_RULE_METHODS (CODE, CREATE_BY, CREATE_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE)
values ('DATA ELEMENT', 1, null, null, null);
